{
	"clients":[
		{
			"name":"A",
			"nric":"X1",
			"gender":"male",
			"nationality":"singaporean"
		},
		{
			"name":"B",
			"nric":"X2",
			"gender":"female",
			"nationality":"singaporeanpr"
		},
		{
			"name":"C",
			"nric":"X3",
			"gender":"male",
			"nationality":"others"
		},
		{
			"name":"D",
			"nric":"X4",
			"gender":"female",
			"nationality":["singaporean", "others"]
		}
	]
}