{
	"title":"Mr",
	"name":"Willy Wonka",
	"nricpp":"1234567",
	"nat":"Singaporean",
	"CoB":"Timbuktoo",
	"gender":"Male",
	"marriage":"Single",
	"dob":"33rd June 2016",
	"isSmoker":"No",
	"address":"Some address somewhere",
	"postcode":"123654",
	"country":"Singapore",
	"race":"Others",
	"language":"English",
	"employment":"selfemployed",
	"EduLvl":"Tertiary and Above",
	"occupation":"$6,000,000 echo slam dunker",
	"employer":"Piecoded",
	"contactHome":"12345678",
	"contactOffice":"-NA-",
	"contactHandphone":"12345678",
	"contactFax":"-NA-",
	"contactEmail":"abc@xyz.com",
	"Income":"Above $15,000",
	"dueDiligenceYesNo":"No",
	
	"exampleListDropdown":"Dropdown Option 1",
	"exampleMapDropdown":"varforoption2",
	"exampleTextInputField":"Default value",
	"exampleDropdownWithHiddenField":"somethingelse"
}